### ISSUE TITLE
install packages

### ISSUE THREAD

**Issue by dmgerman** [SiRumCz/Researches-on-NPM-public-packages#10]
Install the following packages:

- screen
- emacs

**Comment by SiRumCz** [comment]
Could you explain what these packages are for and how(and where) should I use them?

**Comment by dmgerman** [comment]
I want to use them when I log in.


Zhe(Kevin) Chen <notifications@github.com> writes:

> Could you explain what these packages are for and how(and where) should I use them?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
Daniel M. German                  "You cannot have the success without
   H. G. Hasler ->                 the failures."
http://turingmachine.org/
http://silvernegative.com/
dmg (at) uvic (dot) ca
replace (at) with @ and (dot) with .

**Comment by SiRumCz** [comment]
installed
