### ISSUE TITLE
commits

### ISSUE THREAD

**Issue by dmgerman** [SiRumCz/Researches-on-NPM-public-packages#8]
where is the commits data? The table is empty.

**Comment by SiRumCz** [comment]
@dmgerman I am not sure why `select count(*)` returns 0 for commits table, but if I do `select * from commits limit xx`, there is the data.

**Comment by SiRumCz** [comment]
I will clean the table and restore the commits data again.

**Comment by SiRumCz** [comment]
commits table was fully restored last week. close
